import "BookstoreViewModel.idl";

namespace Bookstore
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Int32 MyProperty;
        BookstoreViewModel MainViewModel{ get; };
        
        
    }
}
